INSERT INTO users (photo, full_name, username, email, phone, password, role) VALUES
('/fotoperfil', 'Maria Luisa Gimenez', 'magimenez_prof', 'maria.gimenez@edpro.edu.br', '11999990000', 'M4ria!2025xy', 'professor'),
('/fotodeperfil', 'Luccas Augusto',    'luccasaugusto79',   'luccas.augusto@edpro.edu.br',  '11988880001', 'L4ucc4s#2025', 'professor'),
('/fotodeperfil', 'Rafael Moretti',    'moretti.rafael',   'rafael.moretti@edpro.edu.br',  '11977770002', 'Raf3lM2025$z', 'professor'),
('/fotodeperfil', 'Camila Duarte',     'camisduuarte',   'camila.duarte@edpro.edu.br',   '11966660003', 'C4m1la!2025ab', 'professor'),
('/fotodeperfil', 'Gislaine Adriano',  'gislaineadriano16', 'gislaine.adriano@edpro.edu.br', '11955550004', 'G1sl4ine2025*', 'professor');

INSERT INTO users (photo, full_name, username, email, phone, password, role) VALUES
('/fotodeperfil','Mariana Alves','marialves','mariana.alves@edpro.edu.br','11933330001','M4r!ana2025xy','aluno'),
('/fotodeperfil','Isabel Cristina Lopes','isabelac','isabela.cristina@edpro.edu.br','11933330002','Is4b3l@2025yz','aluno'),
('/fotodeperfil','Fernanda Souza','fernandas','fernanda.souza@edpro.edu.br','11933330003','F3rn@2025abcd','aluno'),
('/fotodeperfil','Sofia Martins','sofiam','sofia.martins@edpro.edu.br','11933330004','S0f1a!2025xz','aluno'),
('/fotodeperfil','Clara Beatriz Oliveira','clarabeatriz','clara.beatriz@edpro.edu.br','11933330005','Cl4r@B!2025op','aluno'),
('/fotodeperfil','Felipe Augusto','felipeaugusto','felipe.augusto@edpro.edu.br','11944440001','F3l!pe2025qw','aluno'),
('/fotodeperfil','Diego Matheus Silva','diegomatheus','diego.matheus@edpro.edu.br','11944440002','D!3goM@2025x','aluno'),
('/fotodeperfil','Gustavo Nunes','gustavon','gustavo.nunes@edpro.edu.br','11944440003','Gust@v0#2025','aluno'),
('/fotodeperfil','Caio Henrique','caiohenrique','caio.henrique@edpro.edu.br','11944440004','C4ioH!2025az','aluno'),
('/fotodeperfil','Thiago Ribeiro','thiagor','thiago.ribeiro@edpro.edu.br','11944440005','Th!ago2025jk','aluno');

INSERT INTO courses (owner_id, photo, title, description, category)VALUES
(1, '/espanhol.jpg', 'Conecta y Crea: Spanish with Purpose','In the course Connect and Create: Spanish with Purpose, you will develop your communication skills from basic greetings to expressing emotions through dynamic and meaningful activities.', 'Language'),
(2, '/lideranca.jpg', 'Humanized Leadership: Inspire, Motivate, and Transform','This course invites leaders, managers, and professionals to rethink the role of leadership in today’s world. Through a human-centered approach, participants will develop skills to inspire their teams, build trust, and turn challenges into opportunities for collective growth.', 'Leadership'),
(3, '/empreendedorismo.jpg', 'From Dream to Action: The Entrepreneur’s Path','Entrepreneurship is more than having a great idea — it’s about turning dreams into real projects. In this course, you’ll learn how to define your purpose, plan strategies, and take action with focus and courage. Through practical and inspiring content, participants will develop an entrepreneurial mindset and learn how to face challenges, manage risks, and seize opportunities in the business world.', 'Entrepreneurship'),
(4, '/equilibrio.jpg', 'Balance and Flow: Stress Management','Modern life demands balance. This course offers practical techniques to recognize, understand, and manage stress while cultivating mindfulness and self-awareness. Through guided exercises and reflections, you’ll learn to reconnect with the present moment, improve concentration, and promote emotional and mental well-being in both personal and professional life.', 'Personal Development'),
(5, '/autoconfianca.jpg', 'You 2.0: Personal Branding and Self-Confidence','Discover the power of your presence and build an authentic personal brand. This course invites you to strengthen your self-confidence, communicate your identity with clarity, and position yourself with purpose in both professional and digital spaces. Through practical activities, reflections, and self-expression strategies, you’ll learn to highlight what makes you unique and turn your potential into positive influence.','Personal Development');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(1, 'The Spanish Alphabet', 'Discovering the Sounds of Spanish','Recognize, pronounce, and write the 27 letters of the Spanish alphabet: Learn to recognize and pronounce each letter of the Spanish alphabet through songs, pronunciation drills, and interactive spelling challenges. Students will practice identifying similarities and differences between Spanish and English letters, improving both pronunciation and listening skills. Activity: Listen to the Spanish alphabet audio and type three Spanish words that contain different sounds.', '/alfabeto.mp4'),
(1, 'Greetings in Spanish', 'Say Hello to the World','Use basic greetings and farewells appropriately in formal and informal situations: In this activity, you will learn how to greet others in different contexts—formal and informal. Practice expressions like ¡Hola! ¿Cómo estás? and Buenos días, while exploring cultural customs related to greetings in Spanish-speaking countries. Activity: Match each greeting to its meaning and record (or type) a short introduction using ¡Hola! and Buenos días.', '/greetings.mp4'),
(1, 'Introducing Yourself in Spanish', 'Who Are You? Let’s Connect!', 'Introduce yourself and others using personal information: Students will practice introducing themselves by saying their name, nationality, age, and where they are from. Through dialogues and role-plays, they’ll learn sentences like “Me llamo Ana. Soy de Brasil.” to confidently present themselves in Spanish. Activity: Write a short paragraph introducing yourself in Spanish (name, nationality, and country of origin).', '/presentation.mp4'),
(1, 'Numbers in Spanish', 'Counting the World Around You', 'Understand, pronounce, and use numbers from 0 to 100 in real situations: Explore numbers from 0 to 100 and beyond! Practice counting, sharing your age, and using numbers in daily contexts such as prices, phone numbers, and dates. Fun games and group exercises will make memorizing numbers easy and enjoyable. Activity: Complete the mini quiz by writing the correct number in Spanish for each digit shown.','/numbers.mp4'),
(1, 'Personal Pronouns', 'Talking About Yourself and Others', 'Identify and correctly use subject pronouns in Spanish: Understand how to use personal pronouns such as yo, tú, él, ella, nosotros, and more. Students will learn how pronouns replace nouns and help build complete sentences, through speaking and writing activities. Activity: Choose the correct pronoun to complete each sentence (yo, tú, él, ella, nosotros, etc.).',
'/pronouns.mp4'),
(1, 'Present Tense (Indicative)', 'Everyday Verbs in Action', 'Use regular and irregular verbs in the present tense to describe routines and actions: Learn how to conjugate and use verbs in the present tense to describe daily routines and actions. With examples like “Yo estudio español” and “Nosotros comemos juntos”, students will gain confidence using regular and irregular verbs. Activity: Fill in the blanks with the correct form of the verb in the present tense.','present_tense.mp4'),
(1, 'Days of the Week and Months of the Year in Spanish', 'Living by the Spanish Calendar', 'Use days, months, and dates in conversation: Discover how to talk about time in Spanish—days, months, and important dates. Students will create a personal calendar in Spanish and practice using expressions such as “Hoy es lunes” and “Mi cumpleaños es en julio”. Activity: Select the correct day or month that matches each sentence.', 'calendar.mp4'),
(1, 'Asking for Help in Spanish', 'Communicate with Confidence', 'Use essential expressions to ask for help and clarification in real situations: Learn essential expressions to ask for help and clarification, such as “¿Puedes ayudarme?” or “No entiendo.” Through situational dialogues, students will gain the confidence to handle real-life interactions in Spanish-speaking environments. Activity: Choose the best phrase to ask for help in each situation.', 'help.mp4'),
(1, 'Interrogative and Exclamatory Pronouns', 'Asking and Expressing with Emotion', 'Form and use questions and exclamations to express curiosity and emotion: Explore how to use question words (qué, cómo, cuándo, dónde, por qué) and exclamatory expressions (¡Qué bonito! ¡Cómo me gusta!) to add curiosity and emotion to your communication. Students will create and answer their own questions in pairs. Activity: Complete each question using the correct interrogative word (qué, cómo, cuándo, dónde, por qué).', 'interrogativos.mp4'),
(1, 'Personality Traits and Character', 'Describing Yourself and Others',
'Learn vocabulary to describe personality, character, and emotions: Learn vocabulary to describe personality and character traits, from simpático to trabajador. Through interviews, matching games, and creative writing, students will express who they are and understand others in Spanish.
Activity: Match each adjective with its English meaning and write two words that describe your personality.',
'personality.mp4');