INSERT INTO users (photo, full_name, username, email, phone, password, role) VALUES
('https://pin.it/3zgRjMHMe', 'Maria Luisa Gimenez', 'magimenez_prof', 'maria.gimenez@edpro.edu.br', '11999990000', 'M4ria!2025xy', 'professor'),
('https://pin.it/1jcrWPy72', 'Luccas Augusto',    'luccasaugusto79',   'luccas.augusto@edpro.edu.br',  '11988880001', 'L4ucc4s#2025', 'professor'),
('https://pin.it/7rRMGgs2x', 'Rafael Moretti',    'moretti.rafael',   'rafael.moretti@edpro.edu.br',  '11977770002', 'Raf3lM2025$z', 'professor'),
('https://pin.it/5aNwc2dPK', 'Camila Duarte',     'camisduuarte',   'camila.duarte@edpro.edu.br',   '11966660003', 'C4m1la!2025ab', 'professor'),
('https://pin.it/4NS9IsWrt', 'Gislaine Adriano',  'gislaineadriano16', 'gislaine.adriano@edpro.edu.br', '11955550004', 'G1sl4ine2025', 'professor');

INSERT INTO users (photo, full_name, username, email, phone, password, role) VALUES
('https://pin.it/3HATo6nh7','Mariana Alves','marialves','mariana.alves@edpro.edu.br','11933330001','M4r!ana2025xy','aluno'),
('https://pin.it/5gHvGqz9L','Isabel Cristina Lopes','isabelac','isabela.cristina@edpro.edu.br','11933330002','Is4b3l@2025yz','aluno'),
('https://pin.it/4uurPZWPo','Fernanda Souza','fernandas','fernanda.souza@edpro.edu.br','11933330003','F3rn@2025abcd','aluno'),
('https://pin.it/wliGUpVas','Sofia Martins','sofiam','sofia.martins@edpro.edu.br','11933330004','S0f1a!2025xz','aluno'),
('https://pin.it/2s776xBum','Clara Beatriz Oliveira','clarabeatriz','clara.beatriz@edpro.edu.br','11933330005','Cl4r@B!2025op','aluno'),
('https://pin.it/7zZ1657Dp','Felipe Augusto','felipeaugusto','felipe.augusto@edpro.edu.br','11944440001','F3l!pe2025qw','aluno'),
('https://pin.it/c9iysgVmW','Diego Matheus Silva','diegomatheus','diego.matheus@edpro.edu.br','11944440002','D!3goM@2025x','aluno'),
('https://pin.it/2F4smJykC','Gustavo Nunes','gustavon','gustavo.nunes@edpro.edu.br','11944440003','Gust@v0#2025','aluno'),
('https://pin.it/48OEvpfPl','Caio Henrique','caiohenrique','caio.henrique@edpro.edu.br','11944440004','C4ioH!2025az','aluno'),
('https://pin.it/4b7nPVM0j','Thiago Ribeiro','thiagor','thiago.ribeiro@edpro.edu.br','11944440005','Th!ago2025jk','aluno');

INSERT INTO courses (owner_id, photo, title, description, category)VALUES
(1, 'https://pin.it/21HF4ZhlK', 'Conecta y Crea: Spanish with Purpose','In the course Connect and Create: Spanish with Purpose, you will develop your communication skills from basic greetings to expressing emotions through dynamic and meaningful activities.', 'Language'),
(2, 'https://pin.it/3UmFI4Xde', 'Humanized Leadership: Inspire, Motivate, and Transform','This course invites leaders, managers, and professionals to rethink the role of leadership in todays world. Through a human-centered approach, participants will develop skills to inspire their teams, build trust, and turn challenges into opportunities for collective growth.', 'Leadership'),
(3, 'https://pin.it/egwl2XoK3', 'From Dream to Action: The Entrepreneurs Path','Entrepreneurship is more than having a great idea — its about turning dreams into real projects. In this course, youll learn how to define your purpose, plan strategies, and take action with focus and courage. Through practical and inspiring content, participants will develop an entrepreneurial mindset and learn how to face challenges, manage risks, and seize opportunities in the business world.', 'Entrepreneurship'),
(4, 'https://pin.it/4eUxGe63W', 'Balance and Flow: Stress Management','Modern life demands balance. This course offers practical techniques to recognize, understand, and manage stress while cultivating mindfulness and self-awareness. Through guided exercises and reflections, youll learn to reconnect with the present moment, improve concentration, and promote emotional and mental well-being in both personal and professional life.', 'Personal Development'),
(5, 'https://pin.it/1qdqBfnmQ', 'You 2.0: Personal Branding and Self-Confidence','Discover the power of your presence and build an authentic personal brand. This course invites you to strengthen your self-confidence, communicate your identity with clarity, and position yourself with purpose in both professional and digital spaces. Through practical activities, reflections, and self-expression strategies, youll learn to highlight what makes you unique and turn your potential into positive influence.', 'Personal Development');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(1, 'The Spanish Alphabet', 'Discovering the Sounds of Spanish','Recognize, pronounce, and write the 27 letters of the Spanish alphabet: Learn to recognize and pronounce each letter of the Spanish alphabet through songs, pronunciation drills, and interactive spelling challenges. Students will practice identifying similarities and differences between Spanish and English letters, improving both pronunciation and listening skills. Activity: Listen to the Spanish alphabet audio and type three Spanish words that contain different sounds.', 'https://youtu.be/KwpdV3aLddw?si=c5nFm0jm9UXALvdw'),
(1, 'Greetings in Spanish', 'Say Hello to the World','Use basic greetings and farewells appropriately in formal and informal situations: In this activity, you will learn how to greet others in different contexts—formal and informal. Practice expressions like ¡Hola! ¿Como estas? and Buenos dias, while exploring cultural customs related to greetings in Spanish-speaking countries. Activity: Match each greeting to its meaning and record (or type) a short introduction using ¡Hola! and Buenos dias.', 'https://youtu.be/jXBaAwoGaFA?si=uLhBWOUwXMaDGZEQ'),
(1, 'Introducing Yourself in Spanish', 'Who Are You? Lets Connect!', 'Introduce yourself and others using personal information: Students will practice introducing themselves by saying their name, nationality, age, and where they are from. Through dialogues and role-plays, theyll learn sentences like “Me llamo Ana. Soy de Brasil.” to confidently present themselves in Spanish. Activity: Write a short paragraph introducing yourself in Spanish (name, nationality, and country of origin).', 'https://youtu.be/i0uwQDZo0Ew?si=BrGhFw0oA7IDpp5s'),
(1, 'Numbers in Spanish', 'Counting the World Around You', 'Understand, pronounce, and use numbers from 0 to 100 in real situations: Explore numbers from 0 to 100 and beyond! Practice counting, sharing your age, and using numbers in daily contexts such as prices, phone numbers, and dates. Fun games and group exercises will make memorizing numbers easy and enjoyable. Activity: Complete the mini quiz by writing the correct number in Spanish for each digit shown.','https://youtu.be/dffV7FSFzCM?si=XzRkvLRrKACzU34x'),
(1, 'Personal Pronouns', 'Talking About Yourself and Others', 'Identify and correctly use subject pronouns in Spanish: Understand how to use personal pronouns such as yo, tu, el, ella, nosotros, and more. Students will learn how pronouns replace nouns and help build complete sentences, through speaking and writing activities. Activity: Choose the correct pronoun to complete each sentence (yo, tu, el, ella, nosotros, etc.).',
'https://youtu.be/-aQc8mhFrk8?si=DniAvmhpPDz2kU8z'),
(1, 'Present Tense (Indicative)', 'Everyday Verbs in Action', 'Use regular and irregular verbs in the present tense to describe routines and actions: Learn how to conjugate and use verbs in the present tense to describe daily routines and actions. With examples like “Yo estudio espanol” and “Nosotros comemos juntos”, students will gain confidence using regular and irregular verbs. Activity: Fill in the blanks with the correct form of the verb in the present tense.','https://youtu.be/lfFsbeKyBKY?si=kNqMRPs-e5mzrVEh'),
(1, 'Days of the Week and Months of the Year in Spanish', 'Living by the Spanish Calendar', 'Use days, months, and dates in conversation: Discover how to talk about time in Spanish—days, months, and important dates. Students will create a personal calendar in Spanish and practice using expressions such as “Hoy es lunes” and “Mi cumpleanos es en julio”. Activity: Select the correct day or month that matches each sentence.', 'https://youtu.be/yNi9teJhT7k?si=ayP1_wXrirhfpQHn'),
(1, 'Asking for Help in Spanish', 'Communicate with Confidence', 'Use essential expressions to ask for help and clarification in real situations: Learn essential expressions to ask for help and clarification, such as “¿Puedes ayudarme?” or “No entiendo.” Through situational dialogues, students will gain the confidence to handle real-life interactions in Spanish-speaking environments. Activity: Choose the best phrase to ask for help in each situation.', 'https://youtu.be/TRRoDD1kvP0?si=Xc4h2nZ4Z69blqeQ'),
(1, 'Interrogative and Exclamatory Pronouns', 'Asking and Expressing with Emotion', 'Form and use questions and exclamations to express curiosity and emotion: Explore how to use question words (que, como, cuando, donde, por que) and exclamatory expressions (¡Qué bonito! ¡Como me gusta!) to add curiosity and emotion to your communication. Students will create and answer their own questions in pairs. Activity: Complete each question using the correct interrogative word (que, como, cuando, donde, por que).', 'https://youtu.be/mvosrOigtN8?si=U43fsBgytZwJJrVi'),
(1, 'Personality Traits and Character', 'Describing Yourself and Others', 'Learn vocabulary to describe personality, character, and emotions: Learn vocabulary to describe personality and character traits, from simpatico to trabajador. Through interviews, matching games, and creative writing, students will express who they are and understand others in Spanish. Activity: Match each adjective with its English meaning and write two words that describe your personality.', 'https://youtu.be/4ncpz8FMx8E?si=iWkM8JSET2doFgYQ');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(2, 'Humanized Leadership', 'Understanding the Concept', 'Understand the foundations of humanized leadership and its impact on modern organizations. Explore how empathy, respect, and authenticity redefine leadership success. Activity: Watch a short video and write one sentence describing what humanized leadership means to you.', 'https://youtu.be/vZ5dCn8HEtA?si=0OD3S4Izr1lLXfRA'),
(2, 'Self-Knowledge and Purpose', 'Leading from Within', 'Identify your personal values, strengths, and purpose as a foundation for authentic leadership. Learn how self-awareness improves decision-making and relationships. Activity: Complete a self-assessment checklist and write three personal values that guide your leadership.', 'https://youtu.be/k71UvTbaMio?si=cs8ppOyokqnz4Kc1'),
(2, 'Empathetic Communication', 'Listening to Understand', 'Develop active listening and empathy to communicate clearly and compassionately with your team. Activity: Read the dialogue examples and select the most empathetic response in each situation.', 'https://youtu.be/8tyFJTtzYtY?si=1-Frj111EoW9zi9g'),
(2, 'Motivation and Engagement', 'Inspiring Your Team', 'Learn strategies to recognize team members motivations and create a culture of enthusiasm and collaboration. Activity: Choose two simple actions you could take this week to motivate your team and share them in the discussion forum.', 'https://youtu.be/X83_UJ4y26I?si=ehha8agjusNkoPcI'),
(2, 'Trust and Credibility', 'The Foundation of Leadership', 'Understand how consistency, transparency, and fairness build trust in professional relationships. Activity: Identify one behavior that strengthens trust and one that weakens it in leadership contexts.', 'https://youtu.be/QmMcSBQvQLQ?si=JhCuCwnYFdqf0olM'),
(2, 'Conflict Management', 'Resolving with Empathy', 'Learn to manage disagreements constructively through active listening and emotional control. Activity: Read the short case study and select the best empathetic approach to resolve the conflict.', 'https://youtu.be/YM3Ye30yTA4?si=N8FehFN12UlZAZBo'),
(2, 'Constructive Feedback', 'Communicate to Grow', 'Develop the ability to give and receive feedback effectively, focusing on improvement and respect.Activity: Choose the best phrasing for feedback in three given examples, focusing on positivity and clarity.', 'https://youtu.be/wtl5UrrgU8c?si=zVKgNuUwy9GD9Nh2'),
(2, 'Inspiring Leadership', 'Leading by Example', 'Explore how authentic and purpose-driven leaders inspire others through their actions and consistency. Activity: Reflect and write one example of a leader who inspires you and what quality makes them stand out.', 'https://youtu.be/JjCFoba5hKE?si=uz8QrnNIkvzvjaKt'),
(2, 'Transformation and Innovation', 'Leading Change', 'Understand how humanized leaders foster innovation, adaptability, and collective transformation in dynamic environments. Activity: Select the leadership behavior that best promotes innovation from the options provided.', 'https://youtu.be/4qEnnf10dhY?si=kekUGcnElhIsrX36'),
(2, 'Humanized Leadership Action Plan', 'From Insight to Practice', 'Apply the course learnings to your professional context by creating a simple action plan for continuous improvement as a leader. Activity: Complete the digital form by defining one concrete action you will take to lead more humanely in your workplace.', 'https://youtu.be/anA_TiUfmbM?si=jQ_jDk_u4CVv-OGq');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(3, 'Discovering Your Purpose', 'The Heart Behind Your Vision', 'Reflect on what drives your entrepreneurial motivation and how your personal values connect to your goals. Activity: Write a short statement that defines your entrepreneurial purpose.', 'https://youtu.be/WzrALzUnZ0g?si=IpgUFjXnlB8KBSz_'),
(3, 'From Idea to Opportunity', 'Turning Inspiration into Impact', 'Learn how to identify real market needs and transform ideas into viable opportunities. Activity: Match examples of business ideas to the market needs they solve.', 'https://youtu.be/Yi1N_fd_N7k?si=3lJrCwYL9eQrksha'),
(3, 'Understanding Your Market', 'See the People, Feel the Needs', 'Explore your target audience and competitors to define your market position. Activity: Choose the audience profile that best fits your product or service.', 'https://youtu.be/GgIwDN4TpsQ?si=sS0F3DVUZuYoLbx-'),
(3, 'Building Your Value Proposition', 'Why Your Idea Matters?', 'Understand what makes your solution unique and how to communicate its value clearly. Activity: Select the best statement that represents a strong value proposition.', 'https://youtu.be/XQVQJmcNlcI?si=r2skfz4g_zDg-I7R'),
(3, 'Planning for Action', 'From Vision to Roadmap', 'Turn dreams into clear, achievable goals and organize your first steps. Activity: Write one short-term and one long-term goal for your project.', 'https://youtu.be/b4YVHTqQPk8?si=RB3kGpaBhFHcJrbT'),
(3, 'Managing Risks and Challenges', 'Facing the Storms with Strategy', 'Learn to anticipate obstacles and build strategies to overcome them. Activity: Identify which type of risk (financial, market, operational) applies to each example shown.', 'https://youtu.be/jfaABy0E6r4?si=mYw6i9pRM9On2NMx'),
(3, 'Building Your Support Network', 'No One Builds Alone', 'Recognize the importance of mentors, partners, and collaborators in business growth. Activity: Choose the type of support that would be most valuable at your current stage.', 'https://youtu.be/NH6w561FEwU?si=kPpgnEF8gn6ICCeH'),
(3, 'Financial Awareness', 'Numbers that Tell Your Story', 'Understand the basics of business finances and the importance of balance between costs and revenue. Activity: Match financial concepts (cost, profit, investment) with their definitions.', 'https://youtu.be/kbYzVFkfCow?si=8vTmFTq0sAyMWNbM'),
(3, 'The Entrepreneurial Mindset', 'Think Bold, Act Resilient', 'Develop resilience, creativity, and adaptability to face business challenges. Activity: Select the behavior that best demonstrates an entrepreneurial mindset.', 'https://youtu.be/JiGJttyiqFs?si=MrmcdTJ_VI3OvLN8'),
(3, 'From Plan to Practice', 'Your First Step to Real Change', 'Take your first concrete step toward turning your idea into action. Activity: Write one simple action you will take to move your project forward.', 'https://youtu.be/f2O6mQkFiiw?si=WRh8FfKHrNRcNKxE');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(4, 'Understanding Stress', 'Recognize the Signs', 'Identify the physical, emotional, and behavioral signs of stress in daily life. Students will explore how stress manifests in the body and mind to improve self-awareness. Activity: Match each stress symptom to its correct category (physical, emotional, or behavioral).', 'https://youtu.be/WuyPuH9ojCE?si=Jfau6ooPwToESaoe'),
(4, 'Causes of Stress', 'What Triggers You?', 'Learn to identify the main sources of personal and professional stress, understanding how internal and external factors influence well-being. Activity: Select the situations that are most likely to generate stress at work or in life.', 'https://youtu.be/v-t1Z5-oPtU?si=k0w8fKnchC5-fkjn'),
(4, 'The Body and Stress', 'Listening to Yourself', 'Understand how stress affects your body, energy levels, and concentration. Recognize signals like fatigue, tension, and restlessness as warning signs. Activity: Choose the body reactions that commonly occur under stress from the list provided.', 'https://youtu.be/Mh4E3xiNGe4?si=KhehUDWrcstwuyDj'),
(4, 'Mindful Breathing', 'Pause and Reset', 'Explore conscious breathing techniques to reduce stress, improve focus, and regain calm in moments of tension. Activity: Follow a guided breathing exercise and select the statement that best describes how you feel after it.', 'https://youtu.be/v-w-vSvi-24?si=xlU55T541dc6hz-L'),
(4, 'Everyday Mindfulness', 'Living the Present Moment', 'Discover how to integrate mindfulness into everyday tasks to reduce anxiety and improve focus on what truly matters. Activity: Reflect and write one daily activity where you can apply mindfulness.', 'https://youtu.be/QTsUEOUaWpY?si=mLNt1eaxT83EjB6f'),
(4, 'Managing Thoughts', 'Reframe Your Mindset', 'Learn to recognize negative or unhelpful thought patterns and replace them with balanced, constructive perspectives. Activity: Choose the most constructive response to each stressful thought example.', 'https://youtu.be/V3vhXQy48jo?si=ntRvplxmGZErN-Eu'),
(4, 'Work–Life Balance', 'Finding Harmony', 'Recognize the importance of setting boundaries and organizing priorities to maintain emotional well-being. Activity: Select the habits that help maintain a balanced routine.', 'https://youtu.be/MPR3o6Hnf2g?si=DEWfOKt35T7NnKpL'),
(4, 'Emotional Awareness', 'Understanding Your Feelings', 'Develop emotional intelligence by identifying, naming, and managing emotions effectively during stressful situations. Activity: Match emotions to appropriate regulation strategies.', 'https://youtu.be/LgUCyWhJf6s?si=Xwv2N4x3wqdC8T9r'),
(4, 'Relaxation Strategies', 'Release and Recover', 'Explore practical relaxation techniques such as stretching, guided imagery, or music to release stress and restore balance. Activity: Identify which relaxation technique best fits each context presented.', 'https://youtu.be/mKW4ZFP8bGY?si=RsOct_cxneGZTjgh'),
(4, 'Personal Well-being Plan', 'Your Path to Balance', 'Create a personalized plan for daily well-being, integrating emotional, physical, and mental health habits. Activity: Write one concrete action you will include in your daily routine to promote balance and well-being.', 'https://youtu.be/-oJawXgAhng?si=Rhb3mo8yEHA4mrSd');

INSERT INTO lessons (course_id, title, subtitle, content, media) VALUES
(5, 'Personal Identity', 'Knowing Yourself First', 'Recognize your values, passions, and unique qualities that shape who you are. Students will explore self-knowledge as the foundation of confidence and authenticity. Activity: Complete a short self-assessment to identify your top three personal strengths.','https://youtu.be/trqDnLNRuSc?si=jzpVDQjeHfebiA2z'),
(5, 'Self-Confidence in Action', 'Believing in Your Potential', 'Understand how confidence influences communication, relationships, and decision-making. Students will learn to identify and reinforce confident behaviors in daily situations. Activity: Choose the statement that best reflects a confident attitude in different situations.', 'https://youtu.be/l_NYrWqUR40?si=j4uylYUW_lPm097a'),
(5, 'Personal Brand', 'What Makes You Unique', 'Learn the key elements of personal branding and how to express your identity authentically in professional and social contexts. Activity: Write a short personal statement that describes how you want to be perceived.', 'https://youtu.be/e8S1L5o-GVc?si=HZ7tJm-l2huxas9f'),
(5, 'Authentic Communication', 'Expressing Your True Self', 'Develop clarity, honesty, and consistency in your communication style to align words and actions. Activity: Select the communication style that best represents authenticity in each scenario.', 'https://youtu.be/y2U6ObHIGA8?si=LJgyRCHvJDYidsQr'),
(5, 'Image and Presence', 'Making a Positive Impression', 'Discover how body language, tone, and posture influence your personal impact and professional relationships. Activity: Match each communication element to its corresponding effect on first impressions.', 'https://youtu.be/3W5JNZBFA1M?si=Q84wpEvGlg0jfirt'),
(5, 'Self-Perception and Feedback', 'Seeing Yourself Clearly', 'Learn to reflect on how others perceive you, interpret feedback constructively, and apply it for personal growth. Activity: Reflect and write one insight about how external feedback can improve your self-image.', 'https://youtu.be/pOQND2fSvnk?si=sbr6gnwhK3tkVCDW'),
(5, 'Professional Positioning', 'Standing Out with Purpose', 'Define your professional goals and align them with your values and personal brand to stand out with authenticity and direction. Activity: Choose the professional positioning strategy that best matches your career objective.', 'https://youtu.be/ITSLgpQyCx8?si=AKTGluLwNOULZFxR'),
(5, 'Digital Presence', 'Building Your Online Reputation', 'Understand how to present your personal brand consistently across digital platforms while maintaining professionalism and authenticity. Activity: Identify which online actions strengthen or weaken your professional image.', 'https://youtu.be/qso8Uvf5ai0?si=U1nl350WSqVy2b6D'),
(5, 'Overcoming Insecurities', 'Transforming Fear into Strength', 'Recognize limiting beliefs, understand their origin, and transform them into empowering perspectives that fuel personal confidence. Activity: Match each insecurity with a positive affirmation that redefines it.', 'https://youtu.be/xTPk3IC2QDY?si=zBUObM2JLBAer1Dq'),
(5, 'Personal Development Plan', 'Becoming Your Best Version', 'Create a clear action plan to strengthen your confidence and build your personal brand over time. Activity: Write one concrete goal and an action you will take to become “You 2.0.”', 'https://youtu.be/cHO_OOpVv0A?si=5fsms6ee3Pz4JCfH');

INSERT INTO enrollments (user_id, course_id) VALUES
(8, 1),  
(9, 2),  
(10, 3), 
(11, 1), 
(12, 3),
(8, 2), 
(9, 1), 
(11, 3);

INSERT INTO progress (enrollment_id, lesson_id, status, completed_at) VALUES
(8, 2, 'incomplete', NULL),
(8, 2, 'incomplete', NULL),
(8, 3, 'incomplete', NULL),
(9, 4, 'incomplete', NULL),
(9, 5, 'incomplete', NULL),
(9, 6, 'incomplete', NULL),
(10, 7, 'incomplete', NULL),
(10, 8, 'incomplete', NULL),
(10, 9, 'incomplete', NULL),
(11, 10, 'incomplete', NULL),
(11, 11, 'incomplete', NULL),
(11, 12, 'incomplete', NULL),
(12, 13, 'incomplete', NULL),
(12, 14, 'incomplete', NULL),
(12, 15, 'incomplete', NULL);